export { default as Header } from './Header'
export { default as About } from './About'
export { default as Team } from './Team'
export { default as Services } from './Services'
export { default as Calculator } from './Calculator'
export { default as Contact } from './Contact'
